spring.application.name=geo-monitor

spring.datasource.url=${GEO_DB_URL}
spring.datasource.username=${GEO_DB_USER}
spring.datasource.password=${GEO_DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true